# coding:utf-8
IMAGE_CODE_EXPIRES_SECONDS = 180 # 图片验证码的有效期,单位秒
MOBILE_CODE_EXPIRES_SECONDS = 300 # 手机验证码的有效期,单位秒
REDIS_AREA_INFO_EXPIRES_SECONDS = 86400 # 地区信息有效期,单位秒
INDEX_PAGE_MAX_HOUSES_NUMBER = 3 # 首页展示房屋数目
REDIS_INDEX_HOUSES_INFO_SECONDS = 600 # 地区信息有效期,单位秒