# coding:utf-8
IMAGE_CODE_EXPIRES_SECONDS = 180 # 图片验证码的有效期,单位秒
MOBILE_CODE_EXPIRES_SECONDS = 300 # 手机验证码的有效期,单位秒
REDIS_AREA_INFO_EXPIRES_SECONDS = 86400 # 地区信息有效期,单位秒
INDEX_PAGE_MAX_HOUSES_NUMBER = 4 # 首页展示房屋数目
REDIS_INDEX_HOUSES_INFO_SECONDS = 3600 # 首页房屋信息有效期,单位秒
REDIS_HOUSE_INFO_EXPIRES_SECONDES = 86400 # 房屋信息过期时间
HOUSE_LIST_PAGE_CAPACITY = 3 # 房源列表页每页显示房屋数目
HOUSE_LIST_PAGE_CACHE_NUM = 2 # 房源列表页每次缓存页面书